package com.example.q.cardmail;

import android.Manifest;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.net.Uri;
import android.os.Environment;
import android.support.v4.content.ContextCompat;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.ImageView;
import android.widget.TextView;
import android.widget.Toast;

import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;

public class CardActivity extends AppCompatActivity {

    String sender;
    String receiver;
    String message;
    Bitmap background;
    int textColor;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_card);

        //Creating card.
        Intent i = getIntent();

        //Receive receiver name.
        String receiverInput = i.getStringExtra("receiver");
        TextView receiverDisplay = (TextView) findViewById(R.id.receiverTextView);
        if (receiverInput != "") {
            receiver = receiverInput;
            //Display receiver.
            receiverDisplay.setText("Dear " + receiver + ",");
        }

        //Receive sender name.
        String senderInput = i.getStringExtra("sender");
        TextView senderDisplay = (TextView) findViewById(R.id.senderTextView);
        if (senderInput != "") {
            sender = senderInput;
            //Display sender.
            senderDisplay.setText(sender);
        }

        //Receive message.
        String messageInput = i.getStringExtra("message");
        TextView messageDisplay = findViewById(R.id.messageTextView);
        if (messageInput != "") {
            message = messageInput;
            //Display message.
            messageDisplay.setText(message);
        }

        //Receive text color.
        textColor = i.getIntExtra("textColor", R.color.defaultTextColor);
        senderDisplay.setTextColor(textColor);
        receiverDisplay.setTextColor(textColor);
        messageDisplay.setTextColor(textColor);

        //Receive background photo.
        String imageUriString = i.getStringExtra("selectedPicture");
        if (imageUriString != null) {
            try {
                Uri imageUri = Uri.parse(i.getStringExtra("selectedPicture"));
                InputStream inputStream = getContentResolver().openInputStream(imageUri);
                background = (Bitmap) BitmapFactory.decodeStream(inputStream);
                //Display background image.
                ImageView backgroundImage = (ImageView) findViewById(R.id.image);
                backgroundImage.setImageBitmap(background);
            } catch (Exception e) {
                e.printStackTrace();
                Toast.makeText(this, "Failed to load image", Toast.LENGTH_LONG).show();
            }
        }

    }

    //Function invoked when SEND button is pressed.
    public void sendCard(View view) {

        View cardImage = findViewById(R.id.card);
        Bitmap card = takescreenshot(cardImage);
        saveAndSend(card);

    }

    public void saveAndSend(Bitmap bitmap) {

        String imageName = "CardFrom" + sender + "To" + receiver;
        String root = Environment.getExternalStorageDirectory().toString() + "/DCIM/Cards/";
        File myDir = new File(root);
        myDir.mkdirs();
        String fname = imageName+ ".jpg";
        File file = new File(myDir, fname);
        if (file.exists()) file.delete();
        Log.i("LOAD", root + fname);
        try {
            FileOutputStream out = new FileOutputStream(file);
            bitmap.compress(Bitmap.CompressFormat.JPEG, 90, out);
            out.flush();
            out.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

        //send email
        Intent emailIntent = new Intent(Intent.ACTION_SENDTO);
        emailIntent.setData(Uri.parse("mailto:"));
        emailIntent.putExtra(Intent.EXTRA_SUBJECT, "Card from " + sender);
        emailIntent.putExtra(Intent.EXTRA_TEXT, "This is an autogenerated mail from S&Y's Card App.");
        emailIntent.putExtra(Intent.EXTRA_STREAM, Uri.fromFile(file));
        if (emailIntent.resolveActivity(getPackageManager()) != null)
            startActivity(emailIntent);
    }

    public static Bitmap takescreenshot (View v) {
        v.setDrawingCacheEnabled(true);
        v.buildDrawingCache(true);
        Bitmap b = Bitmap.createBitmap(v.getDrawingCache());
        v.setDrawingCacheEnabled(false);
        return b;
    }

    // Checks if external storage is available for read and write
    public static boolean isExternalStorageWritable() {
        String state = Environment.getExternalStorageState();
        if (Environment.MEDIA_MOUNTED.equals(state)) {
            return true;
        }
        return false;
    }

}
